version: '3.8'

services:
  app:
    image: fouratchawech/fouratchawech-4twin1-kaddem
    container_name: fouratchawech-4twin1-kaddem
    build:
      context: .
      dockerfile: Dockerfile  # Optionnel si le fichier s'appelle "Dockerfile"
    ports:
      - "8089:8089"
    environment:
      # ===== Configuration Serveur =====
      SERVER_PORT: 8089
      SERVER_SERVLET_CONTEXT_PATH: /kaddem

      # ===== Configuration H2 Obligatoire =====

      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver

      # ===== Authentification H2 (Optionnel) =====
      SPRING_DATASOURCE_USERNAME: fourat
      SPRING_DATASOURCE_PASSWORD: "123"

      # ===== Console H2 =====
      SPRING_H2_CONSOLE_ENABLED: "true"
      SPRING_H2_CONSOLE_PATH: /h2-console
      SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS: "true"  # Accès depuis l'extérieur

      # ===== Configuration JPA/Hibernate =====
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # Auto-mise à jour du schéma
      SPRING_JPA_SHOW_SQL: "true"            # Afficher les requêtes SQL (optionnel)
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"  # Formatage SQL (optionnel)
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "*"
      MANAGEMENT_ENDPOINTS_WEB_BASE_PATH: /actuator

  prometheus:
    image: prom/prometheus
    container_name: kaddemdevops-prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - node-exporter
    networks:
      - monitoring-net

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    networks:
      - monitoring-net

  grafana:
    image: grafana/grafana:latest
    container_name: kaddem-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: 'admin'  # Choisis un mot de passe pour l'admin de Grafana
    depends_on:
      - prometheus
    networks:
      - monitoring-net

volumes:
  grafana-storage:

networks:
  monitoring-net:
    driver: bridge
