FROM openjdk:8-jdk-alpine
EXPOSE 8089
ADD http://192.168.163.131:8081/repository/maven-snapshots/tn/esprit/spring/kaddem/0.0.1-SNAPSHOT/kaddem-0.0.1-20250412.223210-11.jar kaddem-0.0.1.jar
ENTRYPOINT ["java","-jar","kaddem-0.0.1.jar"]
192.168.163.131
